## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,0,Yining,CN,74.46,clear sky,29.04,114.56,Xiushui Hotel
1,2,Marsa Matruh,EG,82.40,clear sky,31.35,27.25,Beau Site
2,6,Ribeira Grande,PT,78.80,few clouds,38.52,-28.70,Quinta da Meia Eira
3,7,Kutum,SD,81.88,broken clouds,14.20,24.67,Dibbo areaمنطقة دبو
4,9,Guerrero Negro,MX,75.15,clear sky,27.98,-114.06,"Casa Laguna, Bed & Breakfast"

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
vacation_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map.
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=vacation_info)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df["City"] == "Izumo"]
vacation_end = vacation_df.loc[vacation_df["City"] == "Izumo"]
vacation_stop1 = vacation_df.loc[vacation_df["City"] == "Katsuura"] 
vacation_stop2 = vacation_df.loc[vacation_df["City"] == "Hasaki"] 
vacation_stop3 = vacation_df.loc[vacation_df["City"] == "Oyama"]

In [6]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start['Lat'].values[0],vacation_start['Lng'].values[0]
end = vacation_end['Lat'].values[0],vacation_end['Lng'].values[0]
stop1 = vacation_stop1['Lat'].values[0],vacation_stop1['Lng'].values[0]
stop2 = vacation_stop2['Lat'].values[0],vacation_stop2['Lng'].values[0]
stop3 =vacation_stop3['Lat'].values[0],vacation_stop3['Lng'].values[0]

In [7]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
japan_trip = gmaps.directions_layer(
    start, end, waypoints=[stop1, stop2, stop3], travel_mode="DRIVING")

In [10]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_df],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,0,Yining,CN,74.46,clear sky,29.04,114.56,Xiushui Hotel
1,2,Marsa Matruh,EG,82.40,clear sky,31.35,27.25,Beau Site
2,6,Ribeira Grande,PT,78.80,few clouds,38.52,-28.70,Quinta da Meia Eira
3,7,Kutum,SD,81.88,broken clouds,14.20,24.67,Dibbo areaمنطقة دبو
4,9,Guerrero Negro,MX,75.15,clear sky,27.98,-114.06,"Casa Laguna, Bed & Breakfast"
...,...,...,...,...,...,...,...,...
307,693,San-Pedro,CI,76.35,overcast clouds,4.75,-6.64,Hotel Maria
308,695,Bonoua,CI,80.60,few clouds,5.27,-3.60,Hotel Bon Samaritian
309,696,Kitaibaraki,JP,73.99,broken clouds,36.78,140.75,Isohara Seaside Hotel
310,698,Zhanakorgan,KZ,81.50,overcast clouds,43.91,67.25,"""Ақпалас"" қонақ үйі"
311,700,Boralday,KZ,75.20,broken clouds,43.36,76.86,Burunday Oteli

In [11]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
itinerary_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [12]:
# 11a. Add a marker layer for each city to the map.
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=vacation_info)
fig.add_layer(marker_layer)
fig.add_layer(japan_trip)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))